apiVersion: v1
kind: Service
metadata:
  name: postgres-public-lb
  labels:
    app: postgres-public
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-public-connection-info
  labels:
    app: postgres-helper
data:
  connection-info.txt: |
    PostgreSQL Public Access Configuration:
    =======================================
    
    1. Deploy this service:
       kubectl apply -f test_postgres_db.yaml
    
    2. Get the external IP address:
       kubectl get service postgres-public-lb
       
    3. Connect from your local pgAdmin 4:
       Host: <EXTERNAL-IP>
       Port: 5432
       Database: (get from: kubectl get configmap postgres-secret -o yaml)
       Username: (get from: kubectl get configmap postgres-secret -o yaml)
       Password: (get from: kubectl get configmap postgres-secret -o yaml)
       SSL Mode: Disable
    
    4. To get the exact database credentials:
       kubectl get configmap postgres-secret -o yaml
    
    5. Clean up when done:
       kubectl delete -f test_postgres_db.yaml
    
    WARNING: This exposes your database to the public internet!
    Only use for testing and remove when finished.
