# Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

title: Corrino
description: Corrino OKE Starter Kit for AI/ML Workloads
informationalText: This OKE Starter Kit is a comprehensive collection of Terraform scripts designed to automate the creation and deployment of resources to easily run AI/ML workloads in OCI. This stack provisions resources such as an OKE cluster, an ATP database instance, and other essential components, which enable you to deploy AI/ML workloads with a simple UI or an API. The kit includes services such as Grafana and Prometheus for infrastructure monitoring, MLFlow for tracking experiment-level metrics, and KEDA for dynamic auto-scaling based on AI/ML workload metrics rather than infrastructure metrics.
schemaVersion: 1.1.0
version: "20190304"

source:
  type: quickstart

locale: "en"

# ------------------------------------------------
# Variable Groups
# ------------------------------------------------

variableGroups:
  -
  - title: "Basic Hidden"
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region
    visible: false

  - title: "Corrino Workspace"
    variables:
    - app_name
    - deploy_id
    - corrino_version

  - title: "Corrino Admin"
    variables:
    - corrino_admin_username
    - corrino_admin_nonce
    - corrino_admin_email

  - title: "Corrino IAM"
    variables:
    - policy_creation_enabled

  - title: "OKE Cluster & VCN"
    variables:
      - existent_oke_cluster_compartment_ocid
      - existent_oke_cluster_id
      - existent_vcn_compartment_ocid
      - existent_vcn_ocid
      - existent_oke_nodes_subnet_ocid
      - existent_oke_load_balancer_subnet_ocid
      - existent_oke_k8s_endpoint_subnet_ocid

  - title: "Public Endpoints"
    variables:
    - ingress_nginx_enabled
    - ingress_hosts
    - fqdn_domain_mode_selector
    - fqdn_custom_domain
    - cert_manager_enabled
    - ingress_tls
    - ingress_cluster_issuer
    - ingress_email_issuer
    visible: true

  - title: "Observability"
    variables:
    - grafana_enabled
    - prometheus_enabled
    - mlflow_enabled
    - nvidia_dcgm_enabled
    visible: true

  - title: "Autoscaling"
    variables:
    - metrics_server_enabled
    - keda_enabled
    visible: true

  - title: "Operational Insight Sharing"
    variables:
    - share_data_with_corrino_team_enabled
    visible: true

  - title: "Autonomous Database"
    variables:
      - autonomous_database_cpu_core_count
      - autonomous_database_data_storage_size_in_tbs
      - autonomous_database_data_safe_status
      - autonomous_database_db_version
      - autonomous_database_license_model
      - autonomous_database_is_auto_scaling_enabled
      - autonomous_database_is_free_tier
      - autonomous_database_wallet_generate_type
      - autonomous_database_visibility
    visible: false

# ------------------------------------------------
# Variables
# ------------------------------------------------

variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  # ---------------------------------
  # OKE Cluster Dependency
  # ---------------------------------

  existent_oke_cluster_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Existent OKE Cluster Compartment"
    description: "The compartment where you find the existent OKE Cluster"
    default: compartment_ocid
    required: true

  existent_vcn_compartment_ocid:
    type: oci:identity:compartment:id
    default: compartment_ocid
    title: "OKE VCN Compartment"
    description: "OKE VCN Compartment"
    required: true

  existent_vcn_ocid:
    type: oci:core:vcn:id
    title: "OKE VCN"
    description: "OKE VCN OCID"
    required: true
    dependsOn:
      compartmentId: existent_vcn_compartment_ocid

  existent_oke_k8s_endpoint_subnet_ocid:
    type: oci:core:subnet:id
    title: "OKE VCN Endpoint Subnet"
    description: "OKE VCN Endpoint Subnet OCID (oke-k8sApiEndpoint)"
    required: true
    dependsOn:
      vcnId: ${existent_vcn_ocid}
      compartmentId: existent_vcn_compartment_ocid


  existent_oke_nodes_subnet_ocid:
    type: oci:core:subnet:id
    title: "Node Subnet"
    description: "OKE VCN Node Subnet OCID (oke-nodesubnet)"
    required: true
    dependsOn:
      vcnId: ${existent_vcn_ocid}
      compartmentId: existent_vcn_compartment_ocid

  existent_oke_load_balancer_subnet_ocid:
    type: oci:core:subnet:id
    title: "Service Load Balancer Subnet"
    description: "OKE VCN Load Balancer Subnet OCID (oke-svclbsubnet)"
    required: true
    dependsOn:
      vcnId: ${existent_vcn_ocid}
      compartmentId: existent_vcn_compartment_ocid

  existent_oke_cluster_id:
    type: oci:container:cluster:id
    title: "OKE Cluster"
    description: "OKE Cluster OCID"
    required: true
    dependsOn:
      compartmentId: existent_oke_cluster_compartment_ocid

  # ---------------------------------
  # Workspace Naming
  # ---------------------------------

  app_name:
    type: string
    title: "Workspace name"
    description: "This is the name that will be assigned for your workspace.  Please provide name that is between 1 and 6 alphanumeric characters in length."
    required: true
    pattern: "^([A-Za-z0-9]){1,6}$"

  deploy_id:
    type: string
    title: "Deploy ID"
    description: "The deployment ID is combined with the workspace name to create a memorable composite name.  Please provide an ID that is between 1 and 6 alphanumeric characters in length."
    pattern: "^([A-Za-z0-9]){1,6}$"
    required: true

  # --------------------
  # Corrino Version
  # --------------------

  corrino_version:
    type: string
    title: "Corrino Version"
    description: "This is the version of Corrino software that will be installed."
    required: true

  # --------------------
  # Corrino Users
  # --------------------

  corrino_admin_username:
    type: string
    title: "Corrino admin username"
    description: "Corrino admin username used to login to API or portal."
    required: true

  corrino_admin_email:
    type: string
    title: "Corrino admin email address"
    description: "Corrino admin email address for tracking who owns this account"
    required: true

  corrino_admin_nonce:
    type: string
    title: "Corrino admin password / nonce"
    description: "Corrino admin password / nonce -- you will be required to change this at first usage"
    required: true

  # --------------------
  # Corrino OCI IAM
  # --------------------

  policy_creation_enabled:
    type: boolean
    title: "Create OCI policy and dynamic group for control plane?"
    required: true

  # --------------------
  # ADB
  # --------------------

  oadb_admin_secret_name:
    visible: false

  oadb_admin_user_name:
    visible: false

  oadb_connection_secret_name:
    visible: false

  oadb_wallet_secret_name:
    visible: false

  # --------------------
  # Credentials
  # --------------------

  private_key_path:
    visible: false

  fingerprint:
    visible: false

  home_region:
    visible: false

  user_ocid:
    visible: false

  # --------------------
  # Corrino Ingress
  # --------------------

  ingress_nginx_enabled:
    type: boolean
    title: "Enable public web access?"
    description: "Enabling this feature requires that a fully qualified domain name be mapped to the resulting load balancer public IP address."

  ingress_hosts:
    type: string
    title: "Optional valid domain name"
    visible: false

  fqdn_domain_mode_selector:
    title: "Domain Options"
    description: "Select which type of domain you want to use for this workspace.  The 'nip.io' default generates a subdomain based on the public IP address associated with your Workspace's load balancer.  If you have a custom domain to use, select 'custom'.  Finally, the 'corrino-oci.com' option requires that you contact the Corrino team to create a DNS A-Record before it can be used."
    type: enum
    # enumerated values
    enum:
    - nip.io
    - corrino-oci.com
    - custom
    default: nip.io
    required: true
    visible:
      and:
        - ingress_nginx_enabled

  fqdn_custom_domain:
    type: string
    title: "Custom domain name"
    required: true
    visible:
      and:
        - ingress_nginx_enabled
        - eq:
          - ${fqdn_domain_mode_selector}
          - custom

  cert_manager_enabled:
    type: boolean
    title: "Certificate Management"
    visible: false

  ingress_tls:
    type: boolean
    title: "Use TLS to enable HTTPS on the valid domain name"
    visible: false

  ingress_cluster_issuer:
    type: enum
    enum:
    - "letsencrypt-prod"
    title: "Certificate Issuer"
    required: true
    visible: false

  ingress_email_issuer:
    type: string
    title: "Certificate Issuer Email"
    required: true
    visible: false

  # ---------------------------------
  # AddOns
  # ---------------------------------

  grafana_enabled:
    type: boolean
    title: "Install Grafana?"
    description: "Kubernetes Grafana is a solution that provides monitoring, visualization, and analytics for Kubernetes"

  prometheus_enabled:
    type: boolean
    title: "Install Prometheus?"
    description: "Prometheus is an open-source monitoring and alerting system that's often used with Kubernetes to monitor containerized applications, APIs, and workloads"

  metrics_server_enabled:
    type: boolean
    title: "Install Kubernetes Metrics Server?"
    description: "The Metrics Server collects resource metrics, such as CPU and memory usage, and makes them available for users to query. It also delivers these metrics to the Kubernetes API server for use by other Kubernetes add-ons, such as the Horizontal Pod Autoscaler (HPA) and the Vertical Pod Autoscaler (VPA)"

  mlflow_enabled:
    type: boolean
    title: "Install MLflow Server?"
    description: "MLflow is a versatile, expandable, open-source platform for managing workflows and artifacts across the machine learning lifecycle. It has built-in integrations with many popular ML libraries, but can be used with any library, algorithm, or deployment tool."

  nvidia_dcgm_enabled:
    type: boolean
    title: "Install NVIDIA DCGM Metrics Exporter?"
    description: "DCGM-Exporter is an exporter for Prometheus to monitor the health and get metrics from GPUs. It leverages DCGM using Go bindings to collect GPU telemetry and exposes GPU metrics to Prometheus using an http endpoint ( /metrics ). DCGM-Exporter can be used either standalone or deployed as part of the NVIDIA GPU Operator"

  keda_enabled:
    type: boolean
    title: "Install Kubernetes Event-driven Autoscaler (KEDA)?"
    description: "KEDA is a tool that allows users to scale Kubernetes workloads based on events or metrics.  It is an Event Driven Autoscaler. With KEDA, you can drive the scaling of any container in Kubernetes based on the number of events needing to be processed"

  # ---------------------------------
  # Data Sharing
  # ---------------------------------

  share_data_with_corrino_team_enabled:
    type: boolean
    title: "Allow your Corrino workspace to share operational insights with Oracle?"
    description: "If enabled, your workspace will securely report limited types of operational insights to Oracle for the purpose of improving the overall experience.  Such reporting will never include any private / sensitive information."

# ------------------------------------------------
# Outputs
# ------------------------------------------------

outputs:

  external_ip:
    visible: true

  corrino_grafana_url:
    visible: true

  corrino_prometheus_url:
    visible: true

  corrino_mlflow_url:
    visible: true

  corrino_api_url:
    visible: true

  corrino_portal_url:
    visible: true

  autonomous_database_password:
    type: string
    title: "DB Admin Password"
    visible: true

  grafana_admin_username:
    type: string
    title: "Grafana Username"
    visible: true

  grafana_admin_password:
    type: string
    title: "Grafana Password"
    visible: true

  deploy_id:
    type: string
    title: "Deploy Id"
    visible: false

  deployed_to_region:
    type: string
    title: "Deployed using Region"
    visible: false

  deployed_oke_kubernetes_version:
    type: string
    title: "OKE Kubernetes version deployed"
    visible: false

  oke_node_pools:
    visible: false

  oke_subnets:
    visible: false

  oke_nodes_subnet:
    visible: false

  cluster_id:
    visible: false

  oke_cluster_ocid:
    visible: false

  kubeconfig:
    visible: false

  kubeconfig_for_kubectl:
    visible: false

  generated_private_key_pem:
    visible: false

  cluster_ca_certificate:
    visible: false

  corrino_source_code:
    visible: false

  corrino_version:
    visible: true

  cluster_region:
    visible: false

  cluster_endpoint:
    visible: false

