# Copyright (c) 2020-2024 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

title: "OCI AI Blueprints Cluster Creation"
description: "Creates a new OKE cluster that is required to deploy OCI AI Blueprints."
informationalText: "This stack provisions a new OKE cluster that is required to deploy OCI AI Blueprints."
schemaVersion: 1.1.0
version: "20190304"

source:
  type: quickstart

locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region
    visible: false

  - title: "Stack Version"
    variables:
    - cluster_creation_stack_version
    visible: true

  - title: "Advanced Configuration?"
    variables: 
    - show_advanced
    
  - title: "Network Configuration"
    variables:
    - network_configuration_mode
    - existing_vcn_id
    - existing_endpoint_subnet_id
    - existing_node_subnet_id
    - existing_lb_subnet_id

  - title: "OKE Cluster Configuration"
    variables:
    - k8s_version
    - cluster_workers_visibility
    - cluster_endpoint_visibility_new_vcn
    - cluster_endpoint_visibility_existing_vcn

  - title: "OKE Worker Nodes"
    variables:
    - num_pool_workers
    - node_pool_instance_shape
    - node_pool_name

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options, allowing enable customer-managed encryption keys, select your ssh key, select/unselect cluster utilities, do not create policies, and other advanced options"
    visible: true

  network_configuration_mode:
    type: enum
    enum:
    - "create_new"
    - "bring_your_own"
    title: "Network Configuration"
    description: "Choose whether to create a new VCN or use an existing one"
    required: true
    visible: true

  existing_vcn_id:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select the existing VCN to use for the OKE cluster"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    visible:
      eq:
        - network_configuration_mode
        - "bring_your_own"

  existing_endpoint_subnet_id:
    type: oci:core:subnet:id
    title: "Existing Kubernetes API Endpoint Subnet"
    description: "Select the existing subnet for the Kubernetes API endpoint"
    required: true
    dependsOn:
      vcnId: existing_vcn_id
      compartmentId: compartment_ocid
    visible:
      eq:
        - network_configuration_mode
        - "bring_your_own"

  existing_node_subnet_id:
    type: oci:core:subnet:id
    title: "Existing Worker Node Subnet"
    description: "Select the existing subnet for worker nodes"
    required: true
    dependsOn:
      vcnId: existing_vcn_id
      compartmentId: compartment_ocid
    visible:
      eq:
        - network_configuration_mode
        - "bring_your_own"

  existing_lb_subnet_id:
    type: oci:core:subnet:id
    title: "Existing Load Balancer Subnet"
    description: "Select the existing subnet for load balancers"
    required: true
    dependsOn:
      vcnId: existing_vcn_id
      compartmentId: compartment_ocid
    visible:
      eq:
        - network_configuration_mode
        - "bring_your_own"

  k8s_version:
    type: enum
    enum: # Necessary hardcoded supported versions, as ORM does not retrieve the versions from OKE.
    - "Latest"
    - "v1.31.1"
    - "v1.30.1"
    - "v1.29.10"
    - "v1.29.1"
    - "1.28.10"
    - "v1.28.2"
    title: "Kubernetes Version"
    required: true
    visible:
      and:
        - show_advanced

  cluster_workers_visibility:
    type: enum
    enum:
    - "Private"
    - "Public"
    title: "Choose Worker Nodes visibility type"
    description: "Note: When using an existing VCN, ensure your subnets are configured appropriately for the chosen visibility"
    required: true
    visible:
      and:
        - show_advanced

  cluster_endpoint_visibility_new_vcn:
    type: enum
    enum:
    - "Public"
    title: "Kubernetes API Endpoint visibility (New VCN)"
    description: "When creating a new VCN, only Public endpoints are supported for simplified setup"
    required: true
    visible:
      and:
        - show_advanced
        - eq:
          - network_configuration_mode
          - "create_new"

  cluster_endpoint_visibility_existing_vcn:
    type: enum
    enum:
    - "Private"
    - "Public"
    title: "Kubernetes API Endpoint visibility (Existing VCN)"
    description: "Choose endpoint visibility for your existing VCN. Ensure your subnets are configured appropriately for the chosen visibility"
    required: true
    visible:
      and:
        - show_advanced
        - eq:
          - network_configuration_mode
          - "bring_your_own"

  num_pool_workers:
    type: integer
    title: "Number of Worker Nodes"
    minimum: 1
    maximum: 1000
    required: true
    visible: true

  node_pool_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a shape for the Worker Nodes instances"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    visible: true

  node_pool_name:
    type: string
    title: "Node Pool Name"
    required: true
    visible:
      and:
        - show_advanced

  cluster_options_add_ons_is_kubernetes_dashboard_enabled:
    type: boolean
    title: "Kubernetes Dashboard Enabled"
    visible: false

  network_cidrs:
    visible: false

  node_pool_boot_volume_size_in_gbs:
    visible: false

  user_ocid:
    visible: false




outputs:

  cluster_creation_stack_version:
    type: string
    title: "Stack Version"
    description: "The version of this stack"
    required: true
    visible: true

  oke_cluster_name:
    type: string
    title: "OKE Cluster Name"
    visible: true

  oke_cluster_id:
    type: ocid
    title: "OKE Cluster OCID"
    visible: true

  oci_ai_blueprints_link_for_section:
    type: link
    title: "Click"
    visible: true
    displayText: "Deploy OCI AI Blueprints onto this Cluster"

  oci_ai_blueprints_link_for_button:
    type: link
    visible: true
    displayText: "Next Step: Deploy OCI AI Blueprints"

  vcn_name:
    type: string
    title: "VCN Name"
    visible: true

  vcn_id:
    type: ocid
    title: "VCN OCID"
    visible: true

  node_subnet_name:
    type: string
    title: "Node Subnet Name"
    visible: true

  lb_subnet_name:
    type: string  
    title: "Load Balancer Subnet Name"
    visible: true

  endpoint_subnet_name:
    type: string
    title: "K8s API Endpoint Subnet Name"
    visible: true

  node_subnet_id:
    type: ocid
    title: "Node Subnet OCID"
    visible: true

  lb_subnet_id: 
    type: ocid
    title: "Load Balancer Subnet OCID"
    visible: true

  endpoint_subnet_id:
    type: ocid  
    title: "K8s API Endpoint Subnet OCID"
    visible: true
outputGroups:
  - title: "Next Step: Deploy OCI AI Blueprints"
    outputs:
      - oci_ai_blueprints_link_for_section


  - title: "Cluster Creation Stack Version"
    outputs:
      - cluster_creation_stack_version

  - title: OKE Cluster Details
    outputs:
      - oke_cluster_name
      - oke_cluster_id

  - title: VCN Details
    outputs:
      - vcn_name
      - vcn_id
      - node_subnet_name
      - node_subnet_id
      - lb_subnet_name
      - lb_subnet_id
      - endpoint_subnet_name
      - endpoint_subnet_id



primaryOutputButton: ${oci_ai_blueprints_link_for_button}

